import time as _time
import os
import hashlib
import hmac
import json
import random
import requests as http_requests
from contextlib import asynccontextmanager
from datetime import datetime, timezone

from fastapi import FastAPI, HTTPException, Security, status, Depends, Request
from fastapi.middleware.cors import CORSMiddleware
from fastapi.security import APIKeyHeader, HTTPAuthorizationCredentials, HTTPBearer
from pydantic import BaseModel
from slowapi import Limiter, _rate_limit_exceeded_handler
from slowapi.util import get_remote_address
from slowapi.errors import RateLimitExceeded
from apscheduler.schedulers.background import BackgroundScheduler
from dotenv import load_dotenv
import jwt

from db import fetch_sensor_readings, get_dashboard_metrics, init_db, save_sensor_reading
from routes.stream import broadcast_data, router as stream_router
from routes.fraud import router as fraud_router, _read_alerts, _write_alerts

# ---------------------------------------------------------------------------
# Environment
# ---------------------------------------------------------------------------
load_dotenv(os.path.join(os.path.dirname(__file__), ".env"))
load_dotenv(os.path.join(os.path.dirname(__file__), "..", ".env"))

API_KEY            = os.getenv("DEPIN_API_KEY")
SECRET_KEY         = os.getenv("JWT_SECRET_KEY")
AI_SERVICE_URL     = os.getenv("AI_SERVICE_URL", "http://localhost:10000/predict")
AI_TIMEOUT_SECONDS = float(os.getenv("AI_TIMEOUT_SECONDS", "4"))
AI_RETRY_COUNT     = int(os.getenv("AI_RETRY_COUNT", "1"))
SENSOR_PAYLOAD_MAX_AGE_SECONDS = int(os.getenv("SENSOR_PAYLOAD_MAX_AGE_SECONDS", "86400"))

# Load anomaly threshold from file generated by ai-service/threshold.py
THRESHOLD_FILE = os.path.join(os.path.dirname(__file__), "..", "ai-service", "threshold.txt")
_ANOMALY_THRESHOLD = 0.087  # fallback default
if os.path.exists(THRESHOLD_FILE):
    try:
        with open(THRESHOLD_FILE, "r") as _tf:
            _ANOMALY_THRESHOLD = float(_tf.read().strip())
    except Exception:
        pass

FRAUD_DB      = os.path.join(os.path.dirname(__file__), "data", "fraud_reports.json")
KNOWN_DEVICES = ["Device-001", "Device-002", "Device-003", "Device-004", "Device-005"]

if not SECRET_KEY:
    raise RuntimeError("JWT_SECRET_KEY is required in .env before starting")

# ---------------------------------------------------------------------------
# In-memory state
# ---------------------------------------------------------------------------
system_state = {
    "dashboard": {
        "active_devices": set(),
        "total_scans":    0,
        "anomalies":      0,
        "uptime":         100.0,
    },
    "blockchain": {
        "total_blocks":   0,
        "transactions":   0,
        "recent_blocks":  [],
    },
    "ai": {
        "total_analyses": 0,
        "anomalies_found": 0,
        "recent_results": [],
    },
    "history": [],
}


def _hydrate_system_state():
    metrics = get_dashboard_metrics()
    recent_history = fetch_sensor_readings(limit=100, newest_first=False)
    critical_history = [record for record in recent_history if record.get("status") == "critical"]

    system_state["dashboard"]["active_devices"] = {
        record.get("device") for record in recent_history if record.get("device")
    }
    system_state["dashboard"]["total_scans"] = metrics["scans"]
    system_state["dashboard"]["anomalies"] = metrics["anomalies"]
    system_state["dashboard"]["uptime"] = metrics["uptime"]

    system_state["ai"]["total_analyses"] = metrics["scans"]
    system_state["ai"]["anomalies_found"] = metrics["anomalies"]
    system_state["ai"]["recent_results"] = [
        {
            "device": record.get("device"),
            "confidence": 0.95,
            "recommendation": record.get("recommendation") or "Alert",
            "timestamp": record.get("timestamp"),
            "severity": "high",
        }
        for record in critical_history[-10:]
    ]

    system_state["blockchain"]["total_blocks"] = metrics["anomalies"]
    system_state["blockchain"]["transactions"] = metrics["anomalies"]
    system_state["blockchain"]["recent_blocks"] = [
        {
            "id": record.get("id"),
            "hash": record.get("hash") or "---",
            "prev_hash": "0000000000000000",
            "timestamp": record.get("timestamp"),
            "status": "Confirmed",
        }
        for record in critical_history[-10:]
    ]

    system_state["history"] = recent_history[-100:]

# ---------------------------------------------------------------------------
# Blockchain integration (optional — falls back to simulation)
# ---------------------------------------------------------------------------
BLOCKCHAIN_ACTIVE = False
try:
    from fabric_manager import fabric_client
    BLOCKCHAIN_ACTIVE = True
except ImportError:
    pass

# ---------------------------------------------------------------------------
# GNN scheduler — writes directly to JSON store
# ---------------------------------------------------------------------------
def run_gnn_analysis():
    history = fetch_sensor_readings(limit=500, newest_first=True)
    if not history:
        print("[GNN] No history yet — skipping analysis run")
        return

    fraud_candidates = [r for r in history if r.get("status") == "critical"]
    if not fraud_candidates:
        print("[GNN] No critical anomalies — no fraud alerts raised")
        return

    alerts = _read_alerts()
    added  = 0
    for rec in fraud_candidates[:3]:
        alert = {
            "timestamp":  datetime.now().isoformat(),
            "asset_id":   rec.get("device", "unknown"),
            "type":       "anomaly_cluster",
            "confidence": round(random.uniform(0.6, 0.99), 4),
        }
        alerts.append(alert)
        added += 1

        # Also write fraud flag to blockchain if network is live
        if BLOCKCHAIN_ACTIVE:
            try:
                evidence_hash = hashlib.sha256(
                    json.dumps(rec, sort_keys=True).encode()
                ).hexdigest()
                fabric_client.submit_transaction("RecordFraudFlag", [
                    rec.get("device", "unknown"),
                    "anomaly_cluster",
                    str(round(alert["confidence"], 4)),
                    evidence_hash,
                    alert["timestamp"],
                ])
            except Exception as exc:
                print(f"[GNN] Blockchain fraud flag write failed: {exc}")

    _write_alerts(alerts)
    print(f"[GNN] Saved {added} fraud alert(s) from {len(fraud_candidates)} critical records")


@asynccontextmanager
async def lifespan(app: FastAPI):
    init_db()
    _hydrate_system_state()
    scheduler = BackgroundScheduler()
    scheduler.add_job(run_gnn_analysis, "interval", minutes=5)
    scheduler.start()
    print(f"[Scheduler] Started — GNN trigger every 5 minutes | threshold={_ANOMALY_THRESHOLD}")
    yield
    scheduler.shutdown()
    print("[Scheduler] Stopped cleanly")


# ---------------------------------------------------------------------------
# App & rate limiting
# ---------------------------------------------------------------------------
limiter = Limiter(key_func=get_remote_address)

app = FastAPI(title="DePIN-Guard API", version="1.0.0", lifespan=lifespan)
app.state.limiter = limiter
app.add_exception_handler(RateLimitExceeded, _rate_limit_exceeded_handler)
app.include_router(stream_router)

# ---------------------------------------------------------------------------
# Security helpers
# ---------------------------------------------------------------------------
api_key_header = APIKeyHeader(name="X-API-Key", auto_error=False)
bearer_scheme  = HTTPBearer(auto_error=True)

if not API_KEY:
    raise RuntimeError("DEPIN_API_KEY is required in .env before starting")

print("✅ API Key loaded")
print(f"✅ Anomaly threshold: {_ANOMALY_THRESHOLD}")
print(f"✅ Blockchain active: {BLOCKCHAIN_ACTIVE}")


async def verify_api_key(api_key: str = Security(api_key_header)):
    if not API_KEY or api_key != API_KEY:
        raise HTTPException(
            status_code=status.HTTP_403_FORBIDDEN,
            detail="Invalid or missing API key",
        )
    return api_key


app.include_router(fraud_router, prefix="/api", dependencies=[Depends(verify_api_key)])

# ---------------------------------------------------------------------------
# CORS
# ---------------------------------------------------------------------------
default_origins = [
    "http://localhost:3000",
    "http://localhost:5173",
    "http://127.0.0.1:3000",
    "http://127.0.0.1:5173",
]
cors_env       = os.getenv("CORS_ALLOWED_ORIGINS", "")
cors_regex_env = os.getenv("CORS_ALLOWED_ORIGIN_REGEX", "").strip()
trusted_origins = (
    [o.strip() for o in cors_env.split(",") if o.strip()]
    or default_origins
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=trusted_origins,
    allow_origin_regex=cors_regex_env or None,
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# ---------------------------------------------------------------------------
# Audit logging middleware
# ---------------------------------------------------------------------------
AUDIT_LOG_PATH = "audit.log"


@app.middleware("http")
async def audit_logger(request: Request, call_next):
    start    = _time.time()
    response = await call_next(request)
    duration = (_time.time() - start) * 1000
    log_line = (
        f"{datetime.now().isoformat()}"
        f"|{request.method}"
        f"|{request.url.path}"
        f"|{response.status_code}"
        f"|{duration:.1f}ms\n"
    )
    with open(AUDIT_LOG_PATH, "a", encoding="utf-8") as log_f:
        log_f.write(log_line)
    return response


# ---------------------------------------------------------------------------
# Data model
# ---------------------------------------------------------------------------
class SensorData(BaseModel):
    device_id:   str
    temperature: float
    vibration:   float
    power_usage: float
    timestamp:   str
    signature:   str = ""


def _sensor_signature(data: SensorData) -> str:
    secret = (API_KEY or "").encode("utf-8")
    message = f"{data.device_id}|{data.temperature}|{data.vibration}|{data.power_usage}|{data.timestamp}"
    return hmac.new(secret, message.encode("utf-8"), hashlib.sha256).hexdigest()


def _verify_sensor_payload(data: SensorData):
    if not data.signature:
        raise HTTPException(status_code=403, detail="Unsigned sensor payload rejected")

    expected = _sensor_signature(data)
    if not hmac.compare_digest(expected, data.signature):
        raise HTTPException(status_code=403, detail="Invalid sensor payload signature")

    try:
        received_at = datetime.fromisoformat(data.timestamp.replace("Z", "+00:00"))
    except Exception:
        raise HTTPException(status_code=400, detail="Invalid timestamp format")

    current_time = datetime.now(timezone.utc)
    received_at_utc = received_at.astimezone(timezone.utc) if received_at.tzinfo else received_at.replace(tzinfo=timezone.utc)
    if SENSOR_PAYLOAD_MAX_AGE_SECONDS > 0 and abs((current_time - received_at_utc).total_seconds()) > SENSOR_PAYLOAD_MAX_AGE_SECONDS:
        raise HTTPException(status_code=403, detail="Sensor payload is stale")


# ---------------------------------------------------------------------------
# Routes
# ---------------------------------------------------------------------------
@app.get("/")
def read_root():
    return {
        "status":           "DePIN-Guard API is live",
        "blockchain_active": BLOCKCHAIN_ACTIVE,
        "threshold":        _ANOMALY_THRESHOLD,
    }


@app.get("/health")
def health_check():
    blockchain_status = {"ready": False, "reason": "fabric manager unavailable"}
    if BLOCKCHAIN_ACTIVE:
        try:
            blockchain_status = fabric_client.network_status()
        except Exception as exc:
            blockchain_status = {"ready": False, "error": str(exc)}
    return {
        "status":            "healthy",
        "service":           "backend",
        "blockchain_active": BLOCKCHAIN_ACTIVE,
        "blockchain_status": blockchain_status,
    }


@app.get("/api/dashboard", dependencies=[Depends(verify_api_key)])
def get_dashboard():
    metrics = get_dashboard_metrics()
    return {
        "stats": metrics,
        "recent_data": fetch_sensor_readings(limit=5, newest_first=True),
    }


@app.get("/api/blockchain", dependencies=[Depends(verify_api_key)])
def get_blockchain():
    return system_state["blockchain"]


@app.get("/api/ai-analysis", dependencies=[Depends(verify_api_key)])
def get_ai_analysis():
    return system_state["ai"]


@app.get("/api/history", dependencies=[Depends(verify_api_key)])
def get_history():
    return fetch_sensor_readings(newest_first=True)


@app.get("/api/history/all", dependencies=[Depends(verify_api_key)])
def get_all_history():
    history = fetch_sensor_readings(newest_first=True)
    return {
        "history": history,
        "count":   len(history),
    }


@app.post("/api/process_data", dependencies=[Depends(verify_api_key)])
@limiter.limit("60/minute")
async def process_data(request: Request, data: SensorData):
    try:
        _verify_sensor_payload(data)
        is_anomaly     = False
        recommendation = "Normal Operation"
        ai_source      = "model"
        ai_result      = {}
        ai_error       = None

        # --- AI inference with retry ---
        for attempt in range(AI_RETRY_COUNT + 1):
            try:
                response = http_requests.post(
                    AI_SERVICE_URL,
                    json=data.dict(),
                    timeout=AI_TIMEOUT_SECONDS,
                )
                ai_result = response.json()
                if ai_result.get("is_anomaly") or ai_result.get("anomaly"):
                    is_anomaly = True
                ai_error = None
                break
            except Exception as exc:
                ai_error = str(exc)
                if attempt < AI_RETRY_COUNT:
                    continue
                # Fallback threshold check when AI service is unreachable
                ai_source = "fallback"
                if data.temperature > 100.0 or data.vibration > 10.0:
                    is_anomaly = True
                print(f"⚠️  AI service unreachable after {AI_RETRY_COUNT + 1} attempts: {exc}")

        # --- Broadcast to WebSocket clients ---
        await broadcast_data({
            "device_id":   data.device_id,
            "temperature": data.temperature,
            "vibration":   data.vibration,
            "power_usage": data.power_usage,
            "is_anomaly":  is_anomaly,
            "timestamp":   datetime.now().isoformat(),
        })

        # --- Update in-memory counters ---
        system_state["dashboard"]["total_scans"] += 1
        system_state["dashboard"]["active_devices"].add(data.device_id)
        system_state["ai"]["total_analyses"] += 1

        status_label = "normal"
        tx_hash      = "---"

        # --- Anomaly path ---
        if is_anomaly:
            if data.temperature > 100:
                recommendation = "CRITICAL: Overheating detected. Check cooling system."
            elif data.vibration > 10:
                recommendation = "WARNING: Severe mechanical vibration. Check mounting."
            else:
                recommendation = "ALERT: AI model detected anomaly pattern."

            status_label = "critical"
            system_state["dashboard"]["anomalies"]       += 1
            system_state["ai"]["anomalies_found"]        += 1
            system_state["blockchain"]["total_blocks"]   += 1
            system_state["blockchain"]["transactions"]   += 1

            # Build data hash for blockchain record
            data_string   = json.dumps(data.dict(), sort_keys=True)
            tx_hash       = hashlib.sha256(data_string.encode()).hexdigest()
            previous_hash = (
                system_state["blockchain"]["recent_blocks"][0]["hash"]
                if system_state["blockchain"]["recent_blocks"]
                else "0000000000000000"
            )

            block_record = {
                "id":        system_state["blockchain"]["total_blocks"],
                "hash":      tx_hash,
                "prev_hash": previous_hash,
                "timestamp": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
                "status":    "Confirmed",
            }
            system_state["blockchain"]["recent_blocks"].insert(0, block_record)
            system_state["blockchain"]["recent_blocks"] = \
                system_state["blockchain"]["recent_blocks"][:10]

            ai_record = {
                "confidence": 95.0,
                "device":         data.device_id,
                "recommendation": recommendation,
                "timestamp":      datetime.now().strftime("%H:%M:%S"),
                "severity":       "high",
            }

            confidence_raw = ai_result.get("anomaly_score")
            if confidence_raw is None:
                confidence_raw = ai_result.get("loss", 0.95)
            try:
                confidence_value = float(confidence_raw)
                if confidence_value <= 1.0:
                    confidence_value *= 100.0
                ai_record["confidence"] = round(max(0.0, min(confidence_value, 100.0)), 2)
            except Exception:
                pass

            system_state["ai"]["recent_results"].insert(0, ai_record)
            system_state["ai"]["recent_results"] = \
                system_state["ai"]["recent_results"][:10]

            # --- Write to Hyperledger Fabric ---
            if BLOCKCHAIN_ACTIVE:
                try:
                    # FIX: was "CreateAsset" which does not exist in custom chaincode.
                    # Correct function is "RecordSensorData" from smartcontract.go.
                    # Signature: RecordSensorData(deviceID, assetType, dataHash,
                    #             isAnomaly, anomalyScore, threshold,
                    #             featureKeysJSON, timestamp)
                    feature_keys_json = json.dumps(["temperature", "vibration", "power_usage"])
                    anomaly_score     = str(round(
                        ai_result.get("anomaly_score", ai_result.get("loss", 0.0)), 6
                    ))
                    tx_result = fabric_client.submit_transaction("RecordSensorData", [
                        data.device_id,
                        "INDUSTRIAL_SENSOR",
                        tx_hash,
                        str(is_anomaly).lower(),   # "true" or "false"
                        anomaly_score,
                        str(_ANOMALY_THRESHOLD),
                        feature_keys_json,
                        data.timestamp,
                    ])
                    if tx_result.get("status") not in ("success", "simulated"):
                        print(f"⚠️  Ledger write non-fatal error: {tx_result.get('error')}")
                except Exception as exc:
                    print(f"⚠️  Ledger write failed (non-fatal): {exc}")

        # --- Append to history ---
        history_record = {
            "device":    data.device_id,
            "hash":      tx_hash,
            "value":     f"{data.temperature}C",
            "timestamp": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
            "status":    status_label,
            "temp":      data.temperature,
            "vib":       data.vibration,
            "pwr":       data.power_usage,
            "anomaly":   is_anomaly,
            "ai_source": ai_source,
            "ai_error":  ai_error,
            "recommendation": recommendation,
        }
        stored_record = save_sensor_reading(history_record)
        history_record["id"] = stored_record["id"]

        system_state["history"].append(history_record)
        if len(system_state["history"]) > 100:
            system_state["history"].pop(0)

        system_state["dashboard"]["total_scans"] = stored_record["id"]
        system_state["dashboard"]["active_devices"].add(data.device_id)

        return {
            "status":    "Processed",
            "anomaly":   is_anomaly,
            "ai_source": ai_source,
            "ai_error":  ai_error,
            "tx_hash":   tx_hash if is_anomaly else None,
        }

    except HTTPException:
        raise
    except Exception as exc:
           import traceback
           error_msg = str(exc) if str(exc) else repr(exc)
           traceback_str = traceback.format_exc()
           print(f"process_data unhandled error: {error_msg}")
           print(f"FULL TRACEBACK:\n{traceback_str}")
           raise HTTPException(status_code=500, detail=f"Error: {error_msg or 'Unknown error'}")


# ---------------------------------------------------------------------------
# JWT verification (used by /submit-data)
# ---------------------------------------------------------------------------
def verify_token(credentials: HTTPAuthorizationCredentials = Depends(bearer_scheme)):
    try:
        payload = jwt.decode(
            credentials.credentials, SECRET_KEY, algorithms=["HS256"]
        )
        return payload
    except Exception:
        raise HTTPException(status_code=401, detail="Invalid or expired token")


@app.post("/submit-data")
@limiter.limit("60/minute")
async def submit_data(request: Request, data: dict, user=Depends(verify_token)):
    await broadcast_data(data)
    return {
        "status": "Data accepted",
        "user":   user.get("user") or user.get("sub") or "unknown",
    }