Organizations:

  - &OrdererOrg
    Name: OrdererMSP
    ID: OrdererMSP
    MSPDir: organizations/ordererOrganizations/orderer.example.com/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('OrdererMSP.member')"
      Writers:
        Type: Signature
        Rule: "OR('OrdererMSP.member')"
      Admins:
        Type: Signature
        Rule: "OR('OrdererMSP.admin')"

  - &Manufacturer
    Name: ManufacturerMSP
    ID: ManufacturerMSP
    MSPDir: organizations/peerOrganizations/manufacturer.example.com/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('ManufacturerMSP.admin', 'ManufacturerMSP.peer', 'ManufacturerMSP.client')"
      Writers:
        Type: Signature
        Rule: "OR('ManufacturerMSP.admin', 'ManufacturerMSP.client')"
      Admins:
        Type: Signature
        Rule: "OR('ManufacturerMSP.admin')"
      Endorsement:
        Type: Signature
        Rule: "OR('ManufacturerMSP.peer')"
    AnchorPeers:
      - Host: peer0.manufacturer.example.com
        Port: 7051

  - &Maintenance
    Name: MaintenanceMSP
    ID: MaintenanceMSP
    MSPDir: organizations/peerOrganizations/maintenance.example.com/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('MaintenanceMSP.admin', 'MaintenanceMSP.peer', 'MaintenanceMSP.client')"
      Writers:
        Type: Signature
        Rule: "OR('MaintenanceMSP.admin', 'MaintenanceMSP.client')"
      Admins:
        Type: Signature
        Rule: "OR('MaintenanceMSP.admin')"
      Endorsement:
        Type: Signature
        Rule: "OR('MaintenanceMSP.peer')"
    AnchorPeers:
      - Host: peer0.maintenance.example.com
        Port: 9051

Capabilities:
  Channel: &ChannelCapabilities
    V2_0: true
  Orderer: &OrdererCapabilities
    V2_0: true
  Application: &ApplicationCapabilities
    V2_0: true

Application: &ApplicationDefaults
  Organizations:
  Policies:
    Readers:
      Type: ImplicitMeta
      Rule: "ANY Readers"
    Writers:
      Type: ImplicitMeta
      Rule: "ANY Writers"
    Admins:
      Type: ImplicitMeta
      Rule: "MAJORITY Admins"
    LifecycleEndorsement:
      Type: ImplicitMeta
      Rule: "MAJORITY Endorsement"
    Endorsement:
      Type: ImplicitMeta
      Rule: "MAJORITY Endorsement"
  Capabilities:
    <<: *ApplicationCapabilities

Orderer: &OrdererDefaults
  OrdererType: solo
  Addresses:
    - orderer.example.com:7050
  BatchTimeout: 2s
  BatchSize:
    MaxMessageCount: 500
    AbsoluteMaxBytes: 10 MB
    PreferredMaxBytes: 2 MB
  Policies:
    Readers:
      Type: ImplicitMeta
      Rule: "ANY Readers"
    Writers:
      Type: ImplicitMeta
      Rule: "ANY Writers"
    Admins:
      Type: ImplicitMeta
      Rule: "MAJORITY Admins"
    BlockValidation:
      Type: ImplicitMeta
      Rule: "ANY Writers"
  Organizations:
  Capabilities:
    <<: *OrdererCapabilities

Channel: &ChannelDefaults
  Policies:
    Readers:
      Type: ImplicitMeta
      Rule: "ANY Readers"
    Writers:
      Type: ImplicitMeta
      Rule: "ANY Writers"
    Admins:
      Type: ImplicitMeta
      Rule: "MAJORITY Admins"
  Capabilities:
    <<: *ChannelCapabilities

Profiles:

  TwoOrgsOrdererGenesis:
    <<: *ChannelDefaults
    Orderer:
      <<: *OrdererDefaults
      Organizations:
        - *OrdererOrg
    Consortiums:
      SampleConsortium:
        Organizations:
          - *Manufacturer
          - *Maintenance

  TwoOrgsChannel:
    Consortium: SampleConsortium
    <<: *ChannelDefaults
    Application:
      <<: *ApplicationDefaults
      Organizations:
        - *Manufacturer
        - *Maintenance
      Capabilities:
        <<: *ApplicationCapabilities