OrdererOrgs:
  - Name: Orderer
    Domain: orderer.example.com
    EnableNodeOUs: true
    Specs:
      - Hostname: orderer
        SANS:
          - "localhost"
          - "127.0.0.1"
          - "orderer.example.com"
          - "orderer.orderer.example.com"

PeerOrgs:
  - Name: Manufacturer
    Domain: manufacturer.example.com
    EnableNodeOUs: true
    Template:
      Count: 1
      SANS:
        - "localhost"
        - "127.0.0.1"
    Users:
      Count: 1

  - Name: Maintenance
    Domain: maintenance.example.com
    EnableNodeOUs: true
    Template:
      Count: 1
      SANS:
        - "localhost"
        - "127.0.0.1"
    Users:
      Count: 1
